version: "3"
services:
  pgbadger:
    image: sdg9670/pgbadger:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: pgbadger
    volumes:
      - ./logs:/pgbadger/logs
      - ./outs:/pgbadger/outs
    environment:
      - "PARAMETERS="
      - "FILE_NAME=postgresql-*.log"
  nginx:
    image: nginx:1.13
    container_name: nginx
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - 1010:80
    volumes:
      - ./outs:/usr/share/nginx/html
    depends_on:
      - pgbadger
